---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express-deployment
  labels:
    app: mongo-express
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
        - name: mongo-express-container
          image: mongo-express
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-express-secret
                  key: mongo-express-admin-username
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-express-secret
                  key: mongo-express-admin-password
            - name: ME_CONFIG_MONGODB_SERVER
              valueFrom:
                configMapKeyRef:
                  name: mongo-express-configmap
                  key: database_url
          ports:
            - containerPort: 8081

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-express-configmap
data:
  database_url: mongodb-service  

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
  labels:
    app: mongo-express
spec:
  selector:
    app: mongo-express
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081

---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-express-secret
type: Opaque
data:
  mongo-express-admin-username: dXNlcm5hbWU= 
  mongo-express-admin-password: TmF2ZWVu       
