apiVersion: apps/v1
kind: Deployment
metadata:
  name: affinity-preffered-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: affinity-preffered
  template:
    metadata:
      labels:
        app: affinity-preffered
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: node-type
                    operator: In
                    values:
                      - arm
      containers:
        - name: affinity-preffered-container
          image: nginx:1.14-alpine
          ports:
            - containerPort: 8000
