apiVersion: apps/v1
kind: Deployment
metadata:
  name: crashloopbackoff-deployment
  namespace: default
  labels:
    app: crashloopbackoff
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crashloopbackoff
  template:
    metadata:
      labels:
        app: crashloopbackoff
    spec:
      containers:
      - name: crashloopbackoff-container
        image: nkalapala24/crashloop:v2
        imagePullPolicy: Always
        ports:
        - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: crashloopbackoff-service
  namespace: default
spec:
  selector:
    app: crashloopbackoff
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
