apiVersion: apps/v1
kind: Deployment
metadata:
  name: livenessprobe-deployment
  namespace: default
  labels:
    app: livenessprobe
spec:
  replicas: 2
  selector:
    matchLabels:
      app: livenessprobe
  template:
    metadata:
      labels:
        app: livenessprobe
    spec:
      containers:
      - name: livenessprobe-container
        image: nkalapala24/liveness-probe:v1
        args:
          - /bin/bash
          - -c
          - touch /tmp/health && sleep 30 && rm -f /tmp/health && sleep 300
        livenessProbe:
          exec:
            command:
              - cat
              - /tmp/health
          initialDelaySeconds: 5
          periodSeconds: 10

        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 8000
        #   initialDelaySeconds: 5
        #   periodSeconds: 10
        # ports:
        # - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: livenessprobe-service
  namespace: default
spec:
  selector:
    app: livenessprobe
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
